// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"backend_institutions/internal/controller"
	"backend_institutions/internal/database"
	"backend_institutions/internal/repository"
	"backend_institutions/internal/routes"
	"backend_institutions/internal/services"
	"github.com/gofiber/fiber/v3"
)

// Injectors from wire.go:

func InitializeApp() (*fiber.App, error) {
	db := database.NewDB()
	userRepository := repository.NewUserRepository(db)
	sessionRepository := repository.NewSessionRepository(db)
	sessionService := services.NewSessionService(sessionRepository)
	userService := services.NewUserService(userRepository, sessionService)
	userController := controller.NewUserController(userService)
	institutionRepository := repository.NewInstitutionRepository(db)
	instituteService := services.NewInstituteService(institutionRepository, userRepository)
	instituteController := controller.NewInstituteController(instituteService)
	departmentRepository := repository.NewDepartmentRepository(db)
	departmentService := services.NewDepartmentService(departmentRepository, userRepository)
	facultyRepository := repository.NewFacultyRepository(db)
	facultyService := services.NewFacultyService(facultyRepository, departmentRepository, userRepository)
	departmentController := controller.NewDepartmentController(departmentService, instituteService, facultyService)
	facultyController := controller.NewFacultyController(facultyService, userService, instituteService)
	principalRepository := repository.NewPrincipalRepository(db)
	principalService := services.NewPrincipalService(principalRepository, departmentRepository, userRepository)
	principalControllers := controller.NewPrincipalControllers(principalService, userService)
	studentRepository := repository.NewStudentRepository(db)
	studentService := services.NewStudentService(studentRepository, facultyRepository, userRepository)
	studentController := controller.NewStudentController(studentService, userService, instituteService, facultyService)
	feesRepository := repository.NewFeesRepository(db)
	feesService := services.NewFeesService(feesRepository, studentRepository, userRepository)
	feesController := controller.NewFeesController(feesService)
	roleRepository := repository.NewRoleRepository(db)
	roleService := services.NewRoleService(roleRepository)
	roleController := controller.NewRoleController(roleService)
	permissionRepository := repository.NewPermissionRepository(db)
	permissionService := services.NewPermissionService(permissionRepository)
	permissionController := controller.NewPermissionController(permissionService)
	menuRepository := repository.NewMenuRepository(db)
	menuService := services.NewMenuService(menuRepository)
	menuController := controller.NewMenuController(menuService)
	app := routes.NewApp(userController, instituteController, departmentController, facultyController, principalControllers, studentController, departmentService, facultyService, principalService, studentService, feesController, roleController, permissionController, menuController, studentRepository, facultyRepository, principalRepository, departmentRepository, feesRepository, userRepository)
	return app, nil
}
