// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"backend_institutions/logger_service/internals/repository"
	"backend_institutions/logger_service/internals/services"
)

// Injectors from wire.go:

func InitializeLoggerService() (*services.LoggerService, error) {
	loggerRepo := repository.NewLoggerRepo()
	loggerService := services.NewLoggerService(loggerRepo)
	return loggerService, nil
}
