// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"backend_institutions/EmailSender/repository"
	"backend_institutions/EmailSender/service"
)

func InitializeNotificationService() (*service.NotificationService, error) {
	emailRepository := repository.NewEmailRepository()
	notificationService := service.NewNotificationService(emailRepository)
	return notificationService, nil
}
