// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: logs/logger.proto

package loggerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          string                 `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Endpoint      string                 `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	Latency       string                 `protobuf:"bytes,6,opt,name=latency,proto3" json:"latency,omitempty"`
	Ip            string                 `protobuf:"bytes,7,opt,name=ip,proto3" json:"ip,omitempty"`
	RequestBody   string                 `protobuf:"bytes,8,opt,name=request_body,json=requestBody,proto3" json:"request_body,omitempty"`
	ResponseBody  string                 `protobuf:"bytes,9,opt,name=response_body,json=responseBody,proto3" json:"response_body,omitempty"`
	Error         string                 `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_logs_logger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logs_logger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_logs_logger_proto_rawDescGZIP(), []int{0}
}

func (x *LogRequest) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *LogRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *LogRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *LogRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *LogRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *LogRequest) GetLatency() string {
	if x != nil {
		return x.Latency
	}
	return ""
}

func (x *LogRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *LogRequest) GetRequestBody() string {
	if x != nil {
		return x.RequestBody
	}
	return ""
}

func (x *LogRequest) GetResponseBody() string {
	if x != nil {
		return x.ResponseBody
	}
	return ""
}

func (x *LogRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type LogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogResponse) Reset() {
	*x = LogResponse{}
	mi := &file_logs_logger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogResponse) ProtoMessage() {}

func (x *LogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logs_logger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogResponse.ProtoReflect.Descriptor instead.
func (*LogResponse) Descriptor() ([]byte, []int) {
	return file_logs_logger_proto_rawDescGZIP(), []int{1}
}

func (x *LogResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LogResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_logs_logger_proto protoreflect.FileDescriptor

const file_logs_logger_proto_rawDesc = "" +
	"\n" +
	"\x11logs/logger.proto\x12\x06logger\"\x8e\x02\n" +
	"\n" +
	"LogRequest\x12\x12\n" +
	"\x04time\x18\x01 \x01(\tR\x04time\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x1a\n" +
	"\bendpoint\x18\x04 \x01(\tR\bendpoint\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x18\n" +
	"\alatency\x18\x06 \x01(\tR\alatency\x12\x0e\n" +
	"\x02ip\x18\a \x01(\tR\x02ip\x12!\n" +
	"\frequest_body\x18\b \x01(\tR\vrequestBody\x12#\n" +
	"\rresponse_body\x18\t \x01(\tR\fresponseBody\x12\x14\n" +
	"\x05error\x18\n" +
	" \x01(\tR\x05error\"A\n" +
	"\vLogResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2N\n" +
	"\rLoggerService\x12=\n" +
	"\x12LogRequestResponse\x12\x12.logger.LogRequest\x1a\x13.logger.LogResponseB6Z4backend_institutions/internal/grpc/loggerpb;loggerpbb\x06proto3"

var (
	file_logs_logger_proto_rawDescOnce sync.Once
	file_logs_logger_proto_rawDescData []byte
)

func file_logs_logger_proto_rawDescGZIP() []byte {
	file_logs_logger_proto_rawDescOnce.Do(func() {
		file_logs_logger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_logs_logger_proto_rawDesc), len(file_logs_logger_proto_rawDesc)))
	})
	return file_logs_logger_proto_rawDescData
}

var file_logs_logger_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_logs_logger_proto_goTypes = []any{
	(*LogRequest)(nil),  // 0: logger.LogRequest
	(*LogResponse)(nil), // 1: logger.LogResponse
}
var file_logs_logger_proto_depIdxs = []int32{
	0, // 0: logger.LoggerService.LogRequestResponse:input_type -> logger.LogRequest
	1, // 1: logger.LoggerService.LogRequestResponse:output_type -> logger.LogResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_logs_logger_proto_init() }
func file_logs_logger_proto_init() {
	if File_logs_logger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_logs_logger_proto_rawDesc), len(file_logs_logger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_logs_logger_proto_goTypes,
		DependencyIndexes: file_logs_logger_proto_depIdxs,
		MessageInfos:      file_logs_logger_proto_msgTypes,
	}.Build()
	File_logs_logger_proto = out.File
	file_logs_logger_proto_goTypes = nil
	file_logs_logger_proto_depIdxs = nil
}
